group_project/compare/urls.py
from django.urls import path
from . import views
from .views import ProblemsView, ProblemDetailView, CreateProblemView, ProblemDetailView, SubmitSolutionView, SolutionView, CompareSolutionsView
# SolutionDetailView

urlpatterns = [
    path('', views.home, name='compare-home'),
    path('about/', views.about, name='compare-about'),
    path('datasets/', views.datasets, name='compare-datasets'),
    path('information/', views.information, name='compare-information'),
    path('myaccount/', views.myaccount, name='compare-myaccount'),
    path('solutions/',views.solutions,name='compare-solutions'),
    path('myproblems/',views.problems,name="compare-problems"),
    path('favourite/',views.favourite,name='compare-favourite'),
    path('problems/', ProblemsView.as_view(), name='problems'),
    path('problems/new/', CreateProblemView.as_view(), name='new_problem'),
    path('problems/<int:pk>/', ProblemDetailView.as_view(), name='problem_detail'),
    path('problems/<int:pk>/submit_solution/', SubmitSolutionView.as_view(), name='submit_solution'),
    path('hostpage/', views.hostpage, name='hostpage'),
    path('acceptDecline/', views.acceptDecline, name='acceptDecline'),
    path('hostProblems/', views.hostProblems, name='hostProblems'),
    path('accepted/', views.accepted, name='accepted'),
    path('rejected/', views.rejected, name='rejected'),
    path('userProblemStatus/', views.userProblemStatus, name='userProblemStatus'),
    path('problems/<int:pk>/solution_list/', SolutionView.as_view(), name='solution_list'),
    path('problems/<int:pk>/compare_solutions/', CompareSolutionsView.as_view(), name='compare_solutions'),
    # path('problems/<int:pk>/solution_list/<int:pk1>/', SolutionDetailView.as_view(), name='solution'),

]

group_project/group_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name ='users/logout.html'), name='logout'),
    path('', include('compare.urls')),
]

group_project/compare/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from .validators import validate_file
from django.db.models.signals import pre_delete, post_delete
from django.dispatch.dispatcher import receiver
from django.forms.models import inlineformset_factory


class Problem(models.Model):
    problemID = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, verbose_name= 'Title')
    problemInfo = models.TextField(verbose_name= 'Problem Details') # max_length=4000
    evaluationCode = models.TextField(verbose_name='Evaluation Code')
    isValid = models.BooleanField(default=False, verbose_name= 'Valid?')
    isReleased = models.BooleanField(default=False, verbose_name= 'Released?')
    localUser = models.ForeignKey(User, on_delete=models.CASCADE, default="", editable=False)
    status = models.CharField(max_length=30, default="Pending")
    dateSubmitted = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"'{self.title}', '{self.problemInfo}', '{self.evaluationCode}', '{self.isValid}', '{self.isReleased}')"

    # def get_absolute_url(self):
    #     return reverse('problem_detail', kwargs={'pk': self.pk})
class Dataset(models.Model):
    dataID = models.AutoField(primary_key=True)
    dataset = models.FileField(upload_to='datasets/', validators=[validate_file])
    datasetDesc = models.CharField(max_length=100, verbose_name= 'Dataset Short Description')
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __str__(self):
        return f"'{self.dataset}', '{self.datasetDesc}'"

    def filename(self):
        return os.path.basename(self.dataset.name)

class Solution(models.Model):
    solutionID = models.AutoField(primary_key=True)
    solutionCode = models.TextField(verbose_name='Solution')
    isVerified = models.BooleanField(default=False)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    localUser = models.ForeignKey(User, on_delete=models.CASCADE, default="", editable=False)
    dateSubmitted = models.DateField(auto_now_add=True)


    def __str__(self):
        return f"'{self.solutionCode}', '{self.isVerified}'"

@receiver(post_delete, sender=Dataset)
def file_delete_handler(sender, **kwargs):
    file = kwargs['instance']
    storage, path = file.dataset.storage, file.dataset.path
    storage.delete(path)



# class Post(models.Model):
#     title = models.CharField(max_length=100)
#     content = models.TextField()
#     date_posted = models.DateTimeField(default=timezone.now)
#     author = models.ForeignKey(User, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.title


# class Datasets(models.Model):
#     title = models.CharField(max_length=100)
#     content = models.TextField()
#     date_posted = models.DateTimeField(default=timezone.now)
#     author = models.CharField(max_length=100)

#     def __str__(self):
#         return self.title

group_project/compare/forms.py
from django import forms

class SubmitProbSpecForm(forms.Form):
	title = forms.CharField(label="Title of Problem Specification")
	description = forms.CharField(widget=forms.Textarea, label="Description: ")
	paste_code = forms.CharField(widget=forms.Textarea, label="Please enter your code here: ")

group_project/compare/views.py
import pymysql
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from utils import sqlhelper
from .models import Problem, Dataset, Solution
from .forms import SubmitProbSpecForm
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from django.forms.models import inlineformset_factory
from django.forms import Textarea, FileInput
from .validators import validate_file
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404

def home(request):
    context = {
        'posts': Problem.objects.filter(status='Accept')
    }
    return render(request, 'compare/home.html', context)

class ProblemsView(ListView):
    template_name = 'compare/problems.html'
    model = Problem
    context_object_name = 'problemsList'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['problemsList'] = Problem.objects.all()
    #     context['solutionList'] = Solution.objects.all()

    #     return context

    # def get_queryset(self):
    #     return Problem.objects.order_by('problemID')

class ProblemDetailView(DetailView):
    model = Problem
    template_name = 'compare/problem_detail.html'

class SolutionDetailView(DetailView):
    model = Solution
    template_name = 'compare/solution.html'

    # def get_context_data(self, **kwargs):
    #     context = super(SolutionDetailView, self).get_context_data(**kwargs)
    #     solution = Solution.objects.get(id=self.kwargs.get('pk1', ''))
    #     context['solution'] = solution
    #     return context

    # def get_success_url(self):
    #     return reverse('solution', kwargs={'pk1': self.object.pk})


childFormset = inlineformset_factory(Problem, Dataset, fields=('dataset', 'datasetDesc',), can_delete=False, extra=1, 
    widgets={'datasetDesc': Textarea(attrs={'required': True}),'dataset': FileInput(attrs={'required': True, 'validators' : validate_file})})

class CreateProblemView(LoginRequiredMixin, CreateView):
    model = Problem
    template_name = 'compare/new_problem.html'
    fields = ['title', 'problemInfo', 'evaluationCode',]
    login_url = 'login'


    def get_context_data(self, **kwargs):
        data = super(CreateProblemView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['datasets'] = childFormset(self.request.POST, self.request.FILES, instance=self.object)
        else:
            data['datasets'] = childFormset(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        datasets = context["datasets"]
        form.instance.localUser = self.request.user
        self.object = form.save()
        if datasets.is_valid():
            datasets.instance = self.object
            datasets.save()
        return super(CreateProblemView, self).form_valid(form)

    def get_success_url(self):
        return reverse('problem_detail', kwargs={'pk': self.object.pk})

class SubmitSolutionView(LoginRequiredMixin, CreateView):
    model = Solution
    template_name = 'compare/submit_solution.html'
    fields = ['solutionCode']
    login_url = 'login'

    def get_success_url(self):
        problemID = self.kwargs['pk']
        return reverse_lazy('problem_detail', kwargs={'pk': problemID})

    def form_valid(self, form):
        problem = get_object_or_404(Problem, pk=self.kwargs['pk'])
        form.instance.problem = problem
        form.instance.localUser = self.request.user
        return super(SubmitSolutionView, self).form_valid(form)

class SolutionView(LoginRequiredMixin, ListView):
    template_name = 'compare/solution_list.html'
    context_object_name = 'solutionList'
    # queryset = 

    def get_queryset(self):
        problemID = self.kwargs['pk']
        # self.problemID = get_object_or_404(Problem, )
        return Solution.objects.filter(problem_id = problemID)

    # def get_success_url(self):
    #     problemID = self.kwargs['pk']
    #     return reverse('solution_list', kwargs={'pk': problemID})
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

class CompareSolutionsView(LoginRequiredMixin, ListView):
    template_name = 'compare/compare_solutions.html'
    context_object_name = 'solutionList'
    # queryset = 

    def get_queryset(self):
        problemID = self.kwargs['pk']
        # self.problemID = get_object_or_404(Problem, )
        return Solution.objects.filter(problem_id = problemID)



def about(request):
    form = SubmitProbSpecForm()
    return render(request, 'compare/about.html', {'form': form})


def datasets(request):
    context = {
        'datasets': Dataset.objects.all()
    }
    return render(request, 'compare/datasets.html', context)


def information(request):
    return render(request, 'compare/information.html', {'title': 'Dataset Information'})


def myaccount(request):
    if request.user.is_authenticated:
        nid = request.user.id
        username = sqlhelper.get_one("select username from auth_user where id=%s", [nid])
        email = sqlhelper.get_one("select email from auth_user where id=%s", [nid])
        print(username)
        if request.method == 'POST':
            nid = request.POST.get('id')
            opw = request.POST.get('Opwd')
            npw = request.POST.get('Npwd')
            cpw = request.POST.get('Cpwd')
            if not request.user.check_password(opw):
                error = "Original Password is Wrong"
                return render(request, 'compare/myaccount.html', {'id': nid, 'username': username, 'email': email, 'error': error})
            if npw != cpw:
                error = "Inconsistent new password entry"
                return render(request, 'compare/myaccount.html', {'id': nid, 'username': username, 'email': email, 'error': error})
            request.user.set_password(npw)
            request.user.save()
            logout(request)
            return render(request, 'compare/home.html')
        return render(request, 'compare/myaccount.html', {'id': nid, 'username': username, 'email': email})
    else:
        return redirect('login')


def solutions(request):
    if request.user.is_authenticated:
        nid = request.user.id
        try:
            solution_list = Solution.objects.filter(localUser=nid).all().values_list("problem__title")
        except Solution.DoesNotExist:
            solution_list = None
        return render(request, 'compare/solutions.html', {'solution_list': solution_list})
    else:
        return redirect('login')


def problems(request):
    if request.user.is_authenticated:
        nid = request.user.id
        try:
            problem_list = Problem.objects.filter(localUser=nid)
        except Problem.DoesNotExist:
            problem_list = None
        return render(request, 'compare/myproblem.html', {'problem_list': problem_list})
    else:
        return redirect('login')


def favourite(request):
    # When having DB, get the userid for post all the information between webpage
    # This sql statement need to be rewrite
    conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='123123', db='mydb', charset='utf8')
    cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)
    cursor.execute("select id, solution from solutions")
    favourite_list = cursor.fetchall()
    cursor.close()
    conn.close()
    return render(request, 'compare/favourite.html', {'favourite_list': favourite_list})


def hostpage(request):
    if request.user.is_superuser:
        return render(request, 'compare/hostpage.html', {'title': 'Host'})
    else:
        return render(request, 'compare/mustbehost.html', {'title': 'Must Be Host'})


def acceptDecline(request):
    if request.user.is_superuser:
        context = {
        'posts': Problem.objects.all()
        }
        if request.method == 'POST':
            post = Problem.objects.get(problemID=request.POST.get('id'))

            if request.POST.get('status'):
                post.status = request.POST.get('status')
                post.save()
        return render(request, 'compare/acceptDecline.html', context, {'title': 'Accept/Reject Problem Specification'})
   
    else:
        return render(request, 'compare/mustbehost.html', {'title': 'Must Be Host'})

def accepted(request):
    if request.user.is_superuser:
        context = {
        'posts': Problem.objects.filter(status='Accept')
        }
        return render(request, 'compare/accepted.html', context, {'title': 'Accepted Problems'})
    else:
        return render(request, 'compare/mustbehost.html', {'title': 'Must Be Host'})


def rejected(request):
    if request.user.is_superuser:
        context = {
        'posts': Problem.objects.filter(status='Reject')
        }
        return render(request, 'compare/rejected.html', context, {'title': 'Rejected Problems'})
    else:
        return render(request, 'compare/mustbehost.html', {'title': 'Must Be Host'})



def hostProblems(request):
    if request.user.is_superuser:
        context = {
        'posts': Problem.objects.filter(status='Accept')
        }
        return render(request, 'compare/hostProblems.html', context, {'title': 'My Hosted Problems'})
    else:
        return render(request, 'compare/mustbehost.html', {'title': 'Must Be Host'})



def userProblemStatus(request):
    if request.user.is_authenticated:
        nid = request.user.id
        try:
            problem_list = Problem.objects.filter(localUser=nid)
        except Problem.DoesNotExist:
            problem_list = None
        return render(request, 'compare/userProblemStatus.html', {'problem_list': problem_list})
    else:
        return redirect('login')

group_project/compare/templates/compare/acceptDecline.html
{% extends "compare/base.html" %}
{% block content %}

        <h3> Accept/Reject Submitted Problem Specifications:</h3>
        <br>
        <h6> For <b>accepted</b> problem specifications <a href="{% url 'accepted' %}">click here</a></h6>
        <h6> For <b>rejected</b> problem specifications <a href="{% url 'rejected' %}">click here</a></h6>
        <br>
        <h4>Pending Problem Specifications:</h4>
        <p class="text-muted"> Note: When declining problem specifications, they will appear in the 'archived' section.</p>
        <br>

    {% for post in posts %}
    <form method="POST">

        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>

        <input type="submit" class="btn btn-info" value="Accept" name="status">
        <input type="submit" class="btn btn-info" value="Reject" name="status">   
        <input type="hidden" name="id" value={{ post.problemID }}></input>
    <br>
    <hr class="solid">
    </form>
    {% endfor %}

{% endblock content %}

group_project/compare/templates/compare/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'compare/main.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    {% if title %}
        <title>Performance Comparison - {{ title }}</title>
    {% else %}
        <title>Performance Comparison</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <a class="navbar-brand" href="{% url 'compare-home' %}">Performance Comparison</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'compare-home' %}">Home <span class="sr-only">Home</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Problem Specifications
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'new_problem' %}">Add Problem</a>
                <a class="dropdown-item" href="{% url 'problems' %}">Solve Problem</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Past Problems</a>
              </div>
            </li>

          </ul>
          <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <div class="dropdown show" style="padding-right: 5px">
                            <a class="btn btn-outline-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'compare-myaccount' %}">My Account</a>
                                <a class="dropdown-item" href="{% url 'compare-solutions' %}">Submitted Solutions</a>
                                <a class="dropdown-item" href="{% url 'compare-problems' %}">Submitted Problems</a>
<!--                                   
                                <a class="dropdown-item" href="{% url 'compare-favourite' %}">Favourite Problems</a>
-->                                
                            </div>
                        </div>
                        <div style="padding-right: 15px">
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        </div>

                            {% if user.is_superuser %}
                              <div style="padding-right: 15px">
                              <a class="nav-item nav-link" href="{% url 'hostpage' %}">Host</a>
                        </div>
                            {% endif %}

                    {% else %}

                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>

                    {% endif %}
                  </div>

          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if message %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Sidebar</h3>
            <p class='text-muted'>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Datasets</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

group_project/compare/templates/compare/compare_solutions.html
{% extends "compare/base.html" %}

{% block content %}
<script>

$(document).ready(function(){
  $("input[name=solutionCheckbox]").change(function(){
    var max= 2;
    if( $("input[name=solutionCheckbox]:checked").length == max ){
        $("input[name=solutionCheckbox]").attr('disabled', 'disabled');
        $("input[name=solutionCheckbox]:checked").removeAttr('disabled');
    }else{
         $("input[name=solutionCheckbox]").removeAttr('disabled');
    }
  });
});

</script>

    <h1>Compare Solutions</h1>
    
    {% for solution in solutionList %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <input type="checkbox" value="{{ solution.solutionID }}" name="solutionCheckbox"> Solution # {{ solution.solutionID }}
              <small class="text-muted">{{ solution.dateSubmitted }}</small>
            </div>
            <h1>Submitted by: {{ solution.localUser.username }}</h1>
            <h2>Solution: <br><br> {{ solution.solutionCode }}</h2>
  <!--          <--/ <p class="article-content">{{ post.content }}</p> -> -->
          </div>
        </article>
    {% endfor %}
{% endblock content %}

<!-- <a class="mr-2" href="{% url 'solution_list' post.solutionID %}"> </a> -->
<!-- Maybe make it so that you click on a link and it shows you the solution -->

group_project/compare/templates/compare/hostProblems.html
{% extends "compare/base.html" %}
{% block content %}

        <h3> Problem Specifications:</h3>
        <br>
        <h4>Currently Hosting:</h4>
        <hr class="solid">
    {% for data in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ data.title }}</a>
              <small class="text-muted">Submitted by: {{ data.localUser }}</small>
            </div>
            <h2><a class="article-title" href="compare/information.html">{{ data.title }}</a></h2>
            <p class="article-content">{{ data.content }}</p>
          </div>
        </article>
        <hr class="solid">

    {% endfor %}



{% endblock content %}

group_project/compare/templates/compare/hostpage.html
{% extends "compare/base.html" %}
{% block content %}

<h1> Comparison Host </h1>

<br>

<div class="container">
  <a type="button" class="btn btn-info btn-block" href="{% url 'acceptDecline' %}">Accept/Decline Problem Specifications</a>
  <a type="button" class="btn btn-info btn-block" href="{% url 'hostProblems' %}">My Problem Specifications</a>
  <br>
  <br>
  <a type="button" class="btn btn-info btn-block" href="http://127.0.0.1:8000/admin/">Access the Admin Page to Add Datasets</a>
</div>

<!-- Current problem specifications that have been added, if added then make it show up on the main page, redirect to admin page in order to add datasets . If deleted put it in an archive, let user know what status of specification is -->


<!-- Current Problem specifications that have are being and have been hosted by you -->

<!-- From this page you can click on each of the problem specifications and see the attempts on them and a ranked order on the users who have the best solutions, the solutions can also be avilable for download -->


{% endblock content %}

group_project/compare/templates/compare/mustbehost.html
{% extends "compare/base.html" %}
{% block content %}

<div class="alert alert-danger">
  <strong>Error!</strong> You must be a host to access this page, please log in if you are a host.
</div>

<h2> </h2>

<a type="button" class="btn btn-info" href="{% url 'login' %}" >Back to Home Page</a>

{% endblock content %}

group_project/compare/templates/compare/problem_detail.html
{% extends 'compare/base.html' %}

{% block content %}
<!-- This needs changing, it is wrong and not linked to anything  -->

<div class="container">
	<h1>Problem Details</h1>
    <hr class="solid">

	<h3>{{ object.title }}</h3> 
	<br>
	<p><b>Description:</b></p>
	<p>{{ object.problemInfo }}</p>
	<br>
	<p><b>Data:</b></p>
	{{object.evaluationCode}}
	<br><br>
	<hr class="solid">
	<a href="{% url 'submit_solution' object.problemID %}">Submit Solution #{{ object.problemID }}</a>
</div>

<br><br><br>

{% endblock content %}

group_project/compare/templates/compare/problems.html
{% extends 'compare/base.html' %}

{% block content %}

<h1>PROBLEMS</h1>

<div class="problems-display">

<table class="problems-table">
	<tr style="font-size: 20px; border-bottom: 1px solid #a3a3c2">
		<th>#</th>
		<th>Title</th>
		<th>Date Posted</th>
		<th>Status</th>
		<th>Solutions</th>
	</tr>
	{% for problem in problemsList %}
	<tr class="problem-list">
		<td style="text-align: center;">{{ forloop.counter }}</td>
		<td width="70%" style="padding-left: 20px;"><a href="{% url 'problem_detail' problem.problemID %}">{{ problem.title }}</a></td>
		<td align="center" width="10%">{{ problem.dateSubmitted|date:"d/m/Y" }}</td>
		<td align="center" width="10%">{{ problem.status }}</td>
		<td align="center">{% if problem.solution_set.count > 0 %} <a href="{% url 'solution_list' problem.problemID %}"> 
			{{ problem.solution_set.count }}
		</a>
		{% else %}
		{{ problem.solution_set.count }}
		{% endif %}

	</td>
	</tr>
	{% endfor %}

</table>	

</div>

{% endblock content %}

group_project/compare/templates/compare/rejected.html
{% extends "compare/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

group_project/compare/templates/compare/solution.html
{% extends 'compare/base.html' %}

{% block content %}
<h1>PROBLEM DETAILS</h1>

<div class="">
	<h2>{{ object.title }}</h2>
	<p>{{ object.problemInfo }}</p>
	<p>{{ object.evaluationCode }}</p>
</div>

{% endblock content %}

group_project/compare/templates/compare/solutions.html
{% extends "compare/base.html" %}
{% block content %}
    <div style="border-bottom:1px solid #aaa;margin: 10px 0;">
    <h1>My Submitted Solutions</h1>
    </div>
    <div>
    <table class="col-sm-12 table table-hover">
        <thead>
        <tr>
            <th>Title</th>
            <th width="15%">Detail</th>
        </tr>
        </thead>
        <tbody>
        {% for row in solution_list %}
        <tr>
            <td style="white-space:nowrap;overflow:hidden;text-overflow: ellipsis;width: 630px;display: inline-block">{{ row.0 }}</td>
            <td><a href="#">Show</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock content %}